
<MyLayout>:
    canvas.before:
        Color:
            rgba:(1,0,1,1)
        Rectangle:
            pos:self.pos
            size:self.size

    BoxLayout:
        size: root.width, root.height
        orientation: 'vertical'
        Label:
            text: 'Name'
            bold:True
        Label:
            text: 'Age'
            color: 1, 0, 0, 1
            background_color: (0, 0, 1, 1)
            bold:True
